### ISSUE TITLE
Investigate Styliner

### ISSUE THREAD

**Issue by jeduan** [niftylettuce/node-email-templates#100]
Read [this post today from the Storify guys](https://medium.com/@Philmod/debugging-node-js-29b2097df36c) where they recommend [Styliner](https://github.com/SLaks/Styliner) over juice2 to close memory leaks.

**Comment by niftylettuce** [comment]
@jeduan we should really look into this.

**Comment by jeduan** [comment]
Had forgotten about this. Definitely.

**Comment by jeduan** [comment]
Juice kept updating and Styliner seems stalled. Closing for now.
