### ISSUE TITLE
Change in juice.js is not backward compatible.

### ISSUE THREAD

**Issue by mystery-man** [niftylettuce/node-email-templates#104]
With the update in juice.js file. The email template is breaking since it's not updated as per required. I've dig into it and seems that the method 'juice' used at line number 78

Code : html = (stylesheet) ? juice(html, stylesheet) : html

is no longer having the arguments (rawhtml , stylesheetObj).
It is changed to juice(filePath, [options], callback)

There is another method added in juice.js 
juice.inlineContent(rawHtml,rawCss) which can be used here

Since the second argument here is rawCss, we have do get the css from Stylesheet object and send to that function.

The code at line number therefore becomes

FROM:
html = (stylesheet) ? juice(html, stylesheet) : html
TO:
html = (stylesheet) ? juice.inlineContent(html, stylesheet.css) : html

Pull Request:
https://github.com/niftylettuce/node-email-templates/pull/105

**Comment by niftylettuce** [comment]
@mystery-man do you also need to bump juice version here <https://github.com/niftylettuce/node-email-templates/blob/master/package.json#L59>?

**Comment by mystery-man** [comment]
@niftylettuce Yes i should have. I forgot that. Thanks for reminding.
