### ISSUE TITLE
Styles not inlined with node 0.11.x

### ISSUE THREAD

**Issue by mileskin** [niftylettuce/node-email-templates#107]
When using latest node 0.11.14 all goes well except generated html doesn't have any inlined styles. I tried with css and less. With 0.10.35 (the last 0.10.x version) everything is perfect. I noticed that allthough `npm install` goes without errors, tests are not run with 0.11.14. #isitjustme

**Comment by bahaagalal** [comment]
I am facing the same issue while using node 0.12.x

**Comment by jeduan** [comment]
0.12 support added in https://github.com/niftylettuce/node-email-templates/pull/114

**Comment by jeduan** [comment]
1.2.0 released. Please check if it solves your issues. If not please create a new issue.
