### ISSUE TITLE
Can't get {{ and }} prefix's to work

### ISSUE THREAD

**Issue by sean-hill** [niftylettuce/node-email-templates#108]
@niftylettuce,

Here's part of my html.ejs

	<td class="content-block">
		Dear {{= name }}, you are awesome.
	</td>

Here's my template options

    var templateOptions = { 
	    open: '{{', close: '}}' 
    };

Here's my locals

    var locals = { name: 'Joe' }

Then

    template(templateName, locals, function(err, html){ ... }

Renders 

    Dear {{= name }}, you are awesome.

:( Any suggestions?

**Comment by rizr** [comment]
I have this problem too, on dev mode -all ok, on production - problem

**Comment by sean-hill** [comment]
So I noticed that the EJS module allows you to pass in custom delimiters, BUT, you still have to put in the `<` and `>`. AKA if you wanted to use `{{` and `}}` as the email templates example shows, you'd have to do `<{{= name }}>`, not just `{{= name }}`. I'm guessing the EJS module updated, but this module hasn't updated their docs just yet.

**Comment by sean-hill** [comment]
Maybe you have different versions of EJS on your machine and on your server? Like you have an older version on your machine, and on your server is the latest version.
