### ISSUE TITLE
Global leaks, CookieAccessInfo, Cookie, CookieJar

### ISSUE THREAD

**Issue by kmpm** [niftylettuce/node-email-templates#112]
I am using v1.1.2 och email-templates and running some tests using http://github.com/hapijs/lab
as a test runner.

As soon as I require the module lab starts to complain about leaks detected.

    The following leaks were detected:CookieAccessInfo, Cookie, CookieJar

Please clean up.

**Comment by jeduan** [comment]
Not sure how can this library leak objects it doesn't use?

**Comment by kmpm** [comment]
it's some dependency of it then. I'll try to pinpoint it.
 Den 17 feb 2015 23:20 skrev "Jeduan Cornejo" <notifications@github.com>:

**Comment by niftylettuce** [comment]
@kmpm any update?
