### ISSUE TITLE
juice2/jsdom dependency, issues with contextify

### ISSUE THREAD

**Issue by mechanicalduck** [niftylettuce/node-email-templates#113]
npm email-template 1.1.2 package on node v0.12.0.

Error during runtime:
````
[...]node_modules/email-templates/node_modules/juice2/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node: undefined symbol: node_module_register
````

With best regards

**Comment by jeduan** [comment]
Should be solved with 1.2.0 (migrated away from juice2), please ensure this is the case and if this persists please open another issue.
