### ISSUE TITLE
Example of hbs partials?

### ISSUE THREAD

**Issue by geoguide** [niftylettuce/node-email-templates#116]
Does anyone have a better example of how to use the partials for handlebars than:

```}, partials: {
    // ...
  }```

If i wanted to include a header and footer and then render the body with a content template in the middle how would I do this? Either it's not clear or I'm too new to handlebars :)

**Comment by vlaurenlee** [comment]
+1 on this. I tried this but got an error back.

    { partials: {
                header: Handlebars.registerPartial("header", path.join(__dirname, 'templates/partials/header.hbs')),
                footer: Handlebars.registerPartial("footer", path.join(__dirname, 'templates/partials/footer.hbs'))
            }

Error: Attempting to register a partial as undefined

**Comment by geoguide** [comment]
emailTemplates('templates', {
			partials: {
				header: fs.readFile('templates/partials/header.hbs')
			}
		},function(err, template) {	

Does not give an fs error but does give:

`Error: The partial header could not be found`

**Comment by geoguide** [comment]
!!!! This works

	emailTemplates('templates', {
			partials: {
				header: fs.readFileSync('templates/partials/header.hbs','utf8')
			}
		},function(err, template) {		

Can we add this to the README please.

**Comment by jeduan** [comment]
Sure can you send a PR?

**Comment by geoguide** [comment]
If you can explain how to commit submodules I can fork it and edit it and send a pull request. :) I've been trying to figure out how to do this for other things I've forked and included in my project but nobody has been able to help me with it.

**Comment by jeduan** [comment]
commit submodules?

**Comment by geoguide** [comment]
My project is in github, I have forked a repo to include in my project and made changes to improve it. I can't figure out how to commit it, the rest of my project commits, but the forked package does not commit. I added it as a submodule because that's apparently the way to do it but it has not worked.

**Comment by jeduan** [comment]
you have to fork this repo, make changes on it and then submit a pull request so your changes can be accepted on this project.

To work locally you can use `npm link`. Here's [a video tutorial I found](https://egghead.io/lessons/node-js-using-npm-link-to-use-node-modules-that-are-in-progress)

**Comment by jeduan** [comment]
Here's a better example
https://github.com/niftylettuce/node-email-templates/blob/v2.0/examples/handlebars/index.js

**Comment by zefexdeveloper** [comment]
@jeduan Is this still working?
