### ISSUE TITLE
Compatibility with node 0.12.X

### ISSUE THREAD

**Issue by julesmqz** [niftylettuce/node-email-templates#117]
# Description
Email styles are not being embedded within the html using node 0.12.x

# Environment

Version | OS | Browser
---------|-------|-----------
Email-templates 1.1.2 | Fedora 20 | Chrome
node 0.12.x | Fedora 20 | Chrome

# Steps to reproduce
- install node 0.12.X
- install email-templates 1.1.2
- install any mail service you want, in my case I used mailgun.
- send an email using email-templates and the style is not gonna be embedded within the html

# Expected results
you should receive an html with styles on your mail.
![html-expected](https://cloud.githubusercontent.com/assets/2530806/6334235/1086f8e8-bb59-11e4-91c5-7026bf040a89.png)

# Evidence
![html-received](https://cloud.githubusercontent.com/assets/2530806/6334236/10871364-bb59-11e4-8b54-0f0b4f74f90f.png)

**Comment by jeduan** [comment]
Hi. version 1.1.2 is not compatible with node >= 0.12. Can you test with >= 1.2.0 and reopen this issue in case the error persists?
