### ISSUE TITLE
Remove reference to stylesheet after inlining?

### ISSUE THREAD

**Issue by cnaccio** [niftylettuce/node-email-templates#122]
Juice has the option to remove the stylesheet reference after inlining; is this possible? When testing compiled templates I'm getting a missing stylesheet error which is due to the stylesheet not being accessible publicly. Any advice is much appreciated.

**Comment by marcucio** [comment]
This info should really be int he readme for this project but you can pass options to juice:

To change juice options:
```
var juiceOptions = { // css inlining tool options, add the options to change here
	preserveMediaQueries: true,
	removeStyleTags: false
}
var locals = {
	juiceOptions: juiceOptions,
	///all other local variables here
};
template('template_name', locals, function(err, html, text) {

```
