### ISSUE TITLE
html template required

### ISSUE THREAD

**Issue by alexandrusavin** [niftylettuce/node-email-templates#127]
Sometimes you might need to send a text only email (ex: business critical emails are usually send in plain-text format ... see amazon.com email address verification message). Now the library forces you to create the html version of the email. 
Why not enforcing one of the two versions and trigger an error only when both are missing. It would still have utility even when you send text only messages as you would anyway use some kind of templating language (like ejs) to compile the message with fields like "name" or "order details" etc.

**Comment by jeduan** [comment]
If there’s a use case, I’ll gladly accept a pull request on the v2 branch for this.

**Comment by alexandrusavin** [comment]
I was actually just forking your project :) but I was working on the master (v1) branch.

As infuriating as it sounds I was required to offer this option in our platform for some (important) messages that don't require "good looks". They argued that if there is the possibility for the sys ops to configure the email servers (or anti-spam servers) to reject html (or multi-part) enabled messages than we will have clients with this configuration on (we're dealing mostly with conservative companies/corporations).

I'll try to patch the v2 branch.

**Comment by jeduan** [comment]
Here’s the relevant lines in case you want to take a stab at it https://github.com/niftylettuce/node-email-templates/blob/v2.0/src/email-template.js#L36-L40 <https://github.com/niftylettuce/node-email-templates/blob/v2.0/src/email-template.js#L36-L40>

**Comment by alexandrusavin** [comment]
I have a pr ready. Please check it as it is my first attempt to es6. Also, can you tell me if v2 is production ready? I just want to avoid surprises as you don't have any releases for this version yet.

**Comment by jeduan** [comment]
Thank you for the PR, it was definitely good.

All tests that were passing on v1 are passing on v2, I don’t have any known bugs left to fix, the things blocking this from being released are more docs and examples

**Comment by alexandrusavin** [comment]
Could you publish a new beta version to NPM? Also, I didn't get the lib forlder when I've installed the beta version through npm and when I try to use it I get "Error: Cannot find module './lib/main'".

If I get some free time I can maybe help with some docs or examples.

**Comment by jeduan** [comment]
Released -beta.1 on npm. Just tested and I'm getting no problems with lib on this build, can you confirm?

**Comment by alexandrusavin** [comment]
Yep! I get the lib folder now. Thank you! I guess we could close this issue now.
