### ISSUE TITLE
Request: Support for Apple Watch Mail

### ISSUE THREAD

**Issue by knightcode** [niftylettuce/node-email-templates#129]
The Apple Watch will display a third version of an email if it exists according to litmus. It's essentially HTML but would require a third file for each template. Any chance of getting support for it?

https://litmus.com/blog/how-to-send-hidden-version-email-apple-watch

**Comment by niftylettuce** [comment]
Let's do it!

**Comment by niftylettuce** [comment]
We can turn off by default and add flag for support?  This probably belongs
in `nodemailer` not in this package though?

**Comment by jeduan** [comment]
I had no idea about this, looks great, and now I have to get an watch to test this, though I can't find any info on which ESPs support `text/watch-html` already

**Comment by knightcode** [comment]
nodemailer gave some love:

https://github.com/andris9/Nodemailer/issues/450
