### ISSUE TITLE
Supporting multi-language support in the templates

### ISSUE THREAD

**Issue by mukulgupta2507** [niftylettuce/node-email-templates#130]
Hi,

I'm using node-email-templates in my project and facing one issue regarding multi-language support for auto-generated emails which are sent from my backend node.js express on successful events like successful registration, password-reset, etc. Can anyone give me some pointers on how to implement it ? 

I'm not able to find any example for implementing it. Also, in my frontend I'm using angular translate for handling multi-lingual translations. Is there any similar node module which can be used with node-email-templates for supporting multi-lingual ?

Thanks

**Comment by mukulgupta2507** [comment]
Anyone who can help me with this ?

**Comment by jeduan** [comment]
Hi Mukul. I think this needs to be resolved at the template level, probably by creating helpers. Not sure what template engine you're using but I remember using handlebars for this by creating a helper, something similar to this http://stackoverflow.com/questions/7760332/how-to-make-i18n-with-handlebars-js-mustache-templates

**Comment by mukulgupta2507** [comment]
Hi Jeduan,

First of all I would like to thank you for taking out time to answer my query. I'm using Jade template with css for styling. Following are my code snippets which I have taken from one of the example:

```
body(bgcolor='#f6f6f6')
  // body
  table.body-wrap(bgcolor='#f6f6f6')
    tr
      td
      td.container(bgcolor='#FFFFFF')
        // content
        .content
          table
            tr
              td
                p Hi,
                p Please confirm your email address by clicking the link below.
                p We may need to send you critical information about our service and it is important that we have an accurate email address.
                table
                  tr
                    td.padding
                      p
                        a.btn-primary(href='http://www.xyz.com') Confirm Email Address
                p Thanks, have a lovely day.
                p -- Team XYZ
                p
                  a(href='http://twitter.com/xyz') Follow @leemunroe on Twitter
        // /content
      td
```

I have created similar directory structure and using a corresponsing style.css. 

In my controller, I'm sending mail using following code:

exports.sendContactFormMail = function (req, res, next) {

```
  var mailOptions = {
    to: config.supportEmail,
    subject: req.body.subject,
    from: req.body.name + ' <' + req.body.email + '>',
    text: req.body.message + " From: "+ "Email: " + req.body.email + " | Contact No.: " + req.body.phone
  };
  console.log(mailOptions);
  transporter.sendMail(mailOptions, function(err, info){
    if (err) {
      console.log(err);
      return res.send(500);
    }else{
      console.log('Message sent: ' + info.response);
      return res.send(200);
    }

    //transporter.close();
  });
};
```

As I have mentioned in my question, I'm using angular-translate in the front-end. Using that transations are really easy to implement in the application. You can simply put all the string in different languages and using {{"som_string"|translate}}, it does automatic conversion. Is there anything similar that I can use for my express backend for automatic translations of email-templates? If not, is there any other way to implement same?

P.S.: I have no idea of handlebars, so understanding that code will be a bit difficult.

**Comment by jeduan** [comment]
You can check out some library like i18next with jade. http://i18next.com/node/pages/doc_templates.html

**Comment by jeduan** [comment]
Please reopen if you couldn't resolve this issue
