### ISSUE TITLE
TypeError : object is not a function

### ISSUE THREAD

**Issue by Kenpa** [niftylettuce/node-email-templates#132]
Hi,

I dont understand why I keep having this error. I'm using postmark btw

Here's my code : 

```javascript
var EmailTemplate = require('email-templates').EmailTemplate;
var templatesDir = path.resolve(__dirname, '../templates');
var template = new EmailTemplate(path.join(templatesDir, 'register'));
var locals = { url : someurl };

template(locals, function (err, results) { ... });
```
The problem is that template is an object and not a function ... here is what I got when I console.log(template) :
```
{ files : {}, 
  path : somepath, 
  dirname : 'register', 
  options : {} 
}
```

**Comment by jeduan** [comment]
Hi! What version of the library are you using? Can you confirm you are on 2.0 by typing `npm update`?

**Comment by jeduan** [comment]
Actually, I see the error. The postmark example is wrong. You should be using

```javascript
template.render(locals, function (err, results) {
  ...
})
```
