### ISSUE TITLE
Minor issue with the Index of the Readme

### ISSUE THREAD

**Issue by Connor-Knabe** [niftylettuce/node-email-templates#133]
Under index at the top of the Readme file 

* [Examples](#examples)
    * [Basic](#basic)
    * [Nodemailer](#nodemailer)
    * [Postmark](#postmark)

Nodemailer and postmark do not redirect properly.

Thanks!

**Comment by jeduan** [comment]
Thanks! Will fix it on the weekend or if you want to, a pull request will be dearly appreciated

**Comment by Connor-Knabe** [comment]
Alright I created a pull request :)

**Comment by jeduan** [comment]
Closed via #134
