### ISSUE TITLE
Bootstrap + Custom Stylesheet

### ISSUE THREAD

**Issue by William-Olson** [niftylettuce/node-email-templates#136]
Is it possible to use bootstrap with node-email-templates as well as a custom stylesheet?

I have tried putting the bootstrap file in the same directory as my template along with my stylus file, but that only inlines the bootstrap and not my custom styles.  

I also tried using juice options trying to pass in the bootstrap css through the extraCss options
```
var bootstrap_css = String(fs.readFileSync(path.join(__dirname, './path_to/bootstrap.css')));
var testEmail = new EmailTemplater(testTemplateDir,
    { 
      juiceOptions: {
        preserveMediaQueries: true,
        removeStyleTags: true,
        extraCss: bootstrap_css
      }
    });
```
I can log the file contents and see all the css, but it isn't getting inlined with my custom styles when I call the render method.

I am going about this wrong here?
I can't figure it out.  Anybody with a bootstrap example that would like to share would help a lot.

**Comment by William-Olson** [comment]
I found a workaround by using gulp to concat bootstrap css file into a custom stylus file. However I pictured the right way to do it being a lot cleaner.

Here was my solution:
```
var gulp = require('gulp')
  , path = require('path')
  , gulp_stylus = require('gulp-stylus')
  , gulp_concat = require('gulp-concat')
  , gulp_filter = require('gulp-filter');

var concatStylus = function (styl_arr, css_arr, out_dest){
  var styles =  (css_arr && css_arr.length > 0) ? styl_arr.concat(css_arr) : styl_arr;
  var filter = gulp_filter('**/*.styl', {restore: true});
  gulp.src(styles)
          .pipe(filter)
          .pipe(gulp_stylus())
          .pipe(filter.restore)
          .pipe(gulp_concat('style.css'))
          .pipe(gulp.dest(out_dest));
};

var mergeBootstrap = function (src_stylus, out_dir){
  concatStylus( [path.join(__dirname, '../path-to-styles/', src_stylus)]
            , [path.join(__dirname, '../path-to-styles/bootstrap.css')]
            , path.join(__dirname, '../path-to-email-templates/', out_dir));
};

mergeBootstrap('test.styl', 'test');
```
Hope this helps anybody in the same boat.  
Would love to see a cleaner solution.

**Comment by jeduan** [comment]
Thank you!
