### ISSUE TITLE
Preview/dev mode

### ISSUE THREAD

**Issue by homerjam** [niftylettuce/node-email-templates#139]
Hi,

Great tool - this fits my needs perfectly.

One option I'd like to have if possible is a way to deactivate juice entirely for development. It seems like my best option at the moment is to build a separate route to render the templates without juice, it'd be more convenient if this were simpler.

Something like:

```js
var devMode = true;

var template = new EmailTemplate(templatePath, {
            juiceOptions: {
                disabled: devMode
            }
        });

        template.render(templateData, function(error, result) {
            if (error) {
                return res.send(error);
            }

            res.send(result);
        });
```

Thanks

**Comment by flore2003** [comment]
I agree, this is a very needed feature!

**Comment by jeduan** [comment]
Hi! I'm kinda curious what do you want to achieve by disabling juice? Your code seems right, I'm kinda confused on what should be different from your perspective

**Comment by homerjam** [comment]
Hi @jeduan 

The trouble is my code doesn't work at the moment as there is no `disabled` option. The reason I'd like to be able to just disable juice is so that every other part of my app can remain the same during template development/testing rather than having to duplicate the functionality of node-email-templates. Basically its a lot slower and more tedious to work on the styling when all the css is inlined!
