### ISSUE TITLE
Issues with node-email-templates, Express and Handlebars

### ISSUE THREAD

**Issue by custa1200** [niftylettuce/node-email-templates#149]
Hi I have a setup that I can send emails with so long as I do not use any handlebars partials. I am using the ExpressJS 4.x built in Handlebars" hbs = require('hbs')" in app.js My setup looks like the following:
```
app.js
|-routes
| |-index.js
| |-send-mail.js
|-views
| |-email-templates
|   |-contact
|     |-html.hbs
| |-partials
    |-email
      |-page-header.hbs
      |-page-footer.hbs 
```

I am wanting to define all my email routes in the send-mail.js route file, but that file does not seem to respect all the Handlebars setup including registering the partials and exposing the locals variables from app.js. My send-email.js looks like:
```
var express = require('express');
var path = require('path');
var EmailTemplate = require('email-templates').EmailTemplate;
var nodemailer = require('nodemailer');
var wellknown = require('nodemailer-wellknown');

var router = express.Router();

var transporter = nodemailer.createTransport({
    service: 'Gmail',
    auth: {
        user: 'xxx@gmail.com',
        pass: 'xxx'
    }
});

var defaultMailOptions = {
    from: 'xxx', // sender address
    toOwner: 'xxx'
};

router.post("/contact", function(req, res) {
    console.log("DIRECTORY NAME: " + __dirname); ///Users/custa/github/Portfolio/portfolioapp/routes
    var templatesDir = path.join(__dirname, '..', 'views', 'email-templates', 'contact');
    var template = new EmailTemplate(templatesDir, {
        juiceOptions: {
            preserveMediaQueries: false,
            removeStyleTags: false
        }
    });
    var body = req.body;
    var currentMailOptions = defaultMailOptions;
    currentMailOptions.subject = "Contact Request";
    currentMailOptions.from = body.email;
    currentMailOptions.senderName = body.name;
    currentMailOptions.message = body.message

    template.render(currentMailOptions, function (err, results) {
        if (err) {
            return console.error(err)
        }

        transporter.sendMail({
            from: currentMailOptions.from,
            to: currentMailOptions.toOwner,
            subject: currentMailOptions.subject,
            html: results.html,
            text: results.text
        }, function (err, responseStatus) {
            if (err) {
                return console.error(err)
            }
            console.log(responseStatus.message)
        });
    });

    res.render('contact-success', {
        title: 'Contact Success - Test'
    });
});

module.exports = router;
```

But when I post to "/contact" I have the following error in the console:

```
DIRECTORY NAME: /Users/custa/github/Portfolio/portfolioapp/routes
{ [Error: The partial email/page-header could not be found]
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  message: 'The partial email/page-header could not be found',
  name: 'Error',
  number: undefined }
```
The "contact/html.hbs" file looks like the following:
```
<html>
    <head></head>
    <body>
        {{>email/page-header}}
        <h1>Contact Request - {{@sitename}}</h1>
        <p>{{senderName}}, sent you the following message from your portfolio site.</p>
        <p>{{message}}</p>
        {{>email/page-footer}}
    </body>
</html>
```
senderName and message work fine when the partials are commented out, but the partials  {{> xxx}} and the local {{@sitename}} do not work.

How do I get node-email-templates to use the Handlebars references that have been set up in App.js and power the non email portion of the site successfuly.

**Comment by jeduan** [comment]
Thanks for the detailed issue description. You could try assigning the handlebars instance manually.

```javascript
var templates = require('email-templates')
templates.requires.handlebars = hbs // instance with partials
```

**Comment by custa1200** [comment]
I assume because of the assignment of his that this goes in the app.js file? I did try it there and still got the same error. I tried to put it into the send-mail.js file but it complains about hbs not being defined.

**Comment by jeduan** [comment]
The idea is to pass the Handlebars instance to `email-templates` but I'm not familiar enough with the package you're using

**Comment by custa1200** [comment]
any recommendation for a handlebars engine if you think the builtin one maybe the issue?

**Comment by custa1200** [comment]
@jeduan is there any chance that I give you access to my repo that you could have a little look?

**Comment by custa1200** [comment]
Is it possible that this is not working because all my templates have an extension of .hbs rather than handlebars?

**Comment by custa1200** [comment]
This is working for me now. I didn't require and set the templates requires in the app.js, when I included the require in both places it worked.

**Comment by divyanksingh** [comment]
@custa1200 can you please elaborate on the solution. I am having the same issue as yours.

**Comment by gzurbach** [comment]
For those using the email-templates v3+ and still want to use handlebars partials, you can do the following:

```js
let email = new Email({
  views: {
    options: {
      extension: 'handlebars'
    }
  }
});

// hbs is your own instance of handlebars, with partials
hbs.registerPartial('html-email-layout', require('views/my-partial.handlebars'));

// Override consolidate's handlebars instance
email.config.views.options.engineSource.requires.handlebars = hbs; 
```

**Comment by Paskalouis** [comment]
@gzurbach 
Hi, thank you for providing hbs partial example for email-templates v3+
But I wonder if we can pass this as config instead of registerPartial directly on handlebars instance ?

I mean like this: 
```javascript
const email = new Email({
            views: {
                options: {
                    extension: 'hbs',
                    partials: {
                        header: `${process.cwd()}/views/emailTemplates/handlebarsEmail/header.hbs`
                    }
                }
            }
        });
```
Unfortunately, the code above is not working.

Thank you
