### ISSUE TITLE
Suggest upgrade to BlueBird 3 version

### ISSUE THREAD

**Issue by ramondeklein** [niftylettuce/node-email-templates#151]
BlueBird recently upgrade to a new major version (v3). I checked the source-code and I think the code will be perfectly capable to work with BB v3. I would suggest allowing this version too.

**Comment by jeduan** [comment]
Actually, I'll be looking into migrating to native promises to reduce the amount of dependencies we're using, but thanks for the tip of bluebird 3!

**Comment by tsm91** [comment]
@jeduan you should check out this [benchmark table.](http://bluebirdjs.com/docs/benchmarks.html) native promises aren't yet performant enough.

```
results for 10000 parallel executions, 1 ms per I/O op

file                                       time(ms)  memory(MB)
promises-bluebird.js                            322       31.92
promises-ecmascript6-native.js                  847      182.71
```

**Comment by jeduan** [comment]
Upgraded to bluebird 3 in 2.1
