### ISSUE TITLE
Css not inlining at all

### ISSUE THREAD

**Issue by arsinawaz** [niftylettuce/node-email-templates#153]
Hi all, 

I am new to node, i have been experiencing issues with css in the email templates. The css file is not taken into consideration by the template. None of my styles are inline in the HTML only the style which i have written explicitly inline in the HTML work and no other styles. Below is my code:

    var path = require('path')
    var EmailTemplate = require('email-templates').EmailTemplate
    var templatesDir = path.join(__dirname, 'templates', 'template1')
    var template = new EmailTemplate(templatesDir)

    var obj = { some json data };
    templete.render(obj, function(err, results){
            if(err){ console.error("Some error occurred while rendering template", err); return; }
            else if(!err){
                  var mailOptions = {
                         from: 'my@email.com', to: obj.email,  subject: 'Subject!',
                         text: results.text, html: results.html
                  };
                  transporter.sendMail(mailOptions, function(error, info){
                        if(error){
                                console.error('Error sending email to: ' + obj.user, error);
                         }else{
                                console.log('Send a confirmation that email sent: ' + info.response);
                         }
                   });
              }
     });

templates/template1/html.ejs

      <!DOCTYPE html>
      <html lang="en">
      <head>    <% include ../partials/head %>  </head>
      <body class="container">
            <header>  <% include ../partials/header %> </header>
            <main><div class="user"><%=user%></div> </main>
             <footer>   <% include ../partials/footer %>   </footer>
      </body>
      </html>

templates/template1/style.ejs

       .user{
            font-weight: bold;
        }

// and other basic styling

templates/template1/text.ejs
-- this one is blank at the moment

templates/partials/head.ejs

      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <style>
            body    { padding-top:50px; }
       </style>

templates/partials/header.ejs

      <nav id="navbar" class="navbar navbar-inverse" role="navigation">
           <div>
                  <a class="navbar-brand pull-left"><img src="cid:logo@pic" class="logo-img"></a>
          </div>
      </nav>

templates/partials/footer.ejs

     <hr style="clear: both;">
     <div class="container">
          <div class="row no-margin">
                  <div class="col-xs-12">
                          <p class="text-center">&copy; 2015 ABC. All rights reserved.</p>
                   </div>
           </div>
     </div>

Any help is appreciated. Thanks in advance.

**Comment by arsinawaz** [comment]
I found the problem in my CSS naming convention, i used classes like '.user-picture' which were only taken into consideration by template when i changed them to 'userPicture'. That's really a strange thing to encounter. But still i am not able to import bootstrap css and inline it to the elements.

**Comment by niftylettuce** [comment]
Try importing it locally.  Download bootstrap with bower or npm, then include relative local path.
