### ISSUE TITLE
styles not being inlined

### ISSUE THREAD

**Issue by jamesdixon** [niftylettuce/node-email-templates#168]
Hi,

I'm not seeing styles inline within my emails whatsoever. For reference, I'm using the Mailgun transactional templates referenced in the README.

My directory structure looks like so:

![image](https://cloud.githubusercontent.com/assets/110114/14997300/509e41a0-113b-11e6-8926-b91e8d8ad6ed.png)

And the code is fairly trivial:

```javascript
const template = new EmailTemplate(Path.join(internals.templatesDir, type));

    return template
        .render(message)
        .then((result) => {

            return internals.sendEmail(
                email,
                subject,
                result.html,
                result.text
            );
        });
```

The email does send with text included, but there is no styling.

Any suggestions?

Thanks,
James

**Comment by row1** [comment]
The file name should be `style` and not `styles`. Also not sure if `.css` is a supported extension, if not then try `style.scss`.

**Comment by killmenot** [comment]
Can confirm that it works with plain css

**Comment by jamesdixon** [comment]
Thanks @row1 -- complete oversight on my part. Appreciate the help!
