### ISSUE TITLE
Cannot call method 'then' of undefined

### ISSUE THREAD

**Issue by radekav** [niftylettuce/node-email-templates#170]
Hi,

Below call to function render throws error like in a title. I can't find why it happens like this. It started to occur after npm install today.

`etpl = new EmailTemplate(templateDir + "/" + tpl.toLowerCase());`
`etpl.render({emailData: emailData}, function(err, result){`

I have checked that some of libraries on which email-templates depends have changed in last days but couldn't find what it can be.

Version of node and npm we have:

node -v v0.10.15
npm -v 1.3.5
email-templates: 2.3.0

Thank you

**Comment by NatalieWolfe** [comment]
The error comes from commit 80589c8fb7656111eefe94c11b77c78dd36be2f1 which wrapped the call to `renderFile` but not the `then` which chained off of it.

**Comment by tomekAppsvisio** [comment]
@NatalieWolfe I have used code from this version https://github.com/niftylettuce/node-email-templates/blob/67294ec4724c6dc0c348bda624a9a408b3178623/src/email-template.js and amended file src/email-template.js. Restarted node server and error still occurs. Any help how to resolve this issue?

**Comment by NatalieWolfe** [comment]
@tomekAppsvisio Did you rebuild the package after modifying that file? If not, I believe you actually need to update `lib/email-template.js`.

**Comment by radekav** [comment]
No I havent rebuild package. Should I do this with npm rebuild email-templates command? 

Thank you
Dnia 05.05.2016 o godz. 17:31 Natalie Wolfe <notifications@github.com> napisał(a):

**Comment by NatalieWolfe** [comment]
@radekav I honestly don't know, I don't maintain this project I just ran into the same issue and narrowed down the source of the problem as that commit.

**Comment by tomekAppsvisio** [comment]
@jeduan could you help in this thing?

**Comment by jeduan** [comment]
@tomekAppsvisio Swamped for 2 weeks.
