### ISSUE TITLE
New feature to use localizable email template in subfolders

### ISSUE THREAD

**Issue by albertosouza** [niftylettuce/node-email-templates#171]
Hi,

A build a small npm module how load node-email-templates and add suport to localization with sub folders for each locale and root fooder for default locale.

Is compatible with default usage of email-template.

Link: https://github.com/albertosouza/email-templates-i18n

Someone can give opinions about my module?

**Comment by niftylettuce** [comment]
very cool, maybe you could build this in directly!  please submit a PR, it'd be great to have this

**Comment by albertosouza** [comment]
ok, i will try ...

**Comment by niftylettuce** [comment]
Is this ready to go @albertosouza ?

**Comment by niftylettuce** [comment]
Released in v2.4.0!

**Comment by niftylettuce** [comment]
This is awesome @albertosouza !!!!! YOU ROCK!!!!! 🚀  🎸  💥  🔥 

LOVE IT ❤️

**Comment by albertosouza** [comment]
Thanks @niftylettuce :thumbsup:
