### ISSUE TITLE
3.X WISHLIST - HAVE AN IDEA/COMMENT/SUGGESTION?

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/node-email-templates#234]
If you have any suggestions, comments, or wishlist items, please post them here for V3.X!

Will be taking your thoughts into consideration 🎉 

- [ ] snyk
- [ ] semaphore
- [ ] codecov
- [ ] `xo`
- [ ] `prettier`
- [ ] `ava`
- [ ] Promises
- [ ] `np`
- [ ] `nyc`
- [ ] examples
- [ ] screencasts/video tutorials
- [ ] service integration
- [ ] logging integration w/cabin
- [ ] dev-based email previewer + `opn` in browser
- [ ] custom fonts in emails <https://github.com/crocodilejs/custom-fonts-in-emails>
- [ ] font awesome assets <https://github.com/crocodilejs/font-awesome-assets>
- [ ] base64 to s3 plugin <https://github.com/crocodilejs/nodemailer-base64-to-s3>
- [ ] i18n/localization/translation support
- [ ] litmus testing
- [ ] markdown + highlightjs
- [ ] analytics
- [ ] bootstrap 4.x
- [ ] default templates

**Comment by niftylettuce** [comment]
pinging power users @jeduan @weisjohn

**Comment by homerjam** [comment]
One feature I think could be (potentially) useful - an option to load templates from a remote source.

**Comment by niftylettuce** [comment]
@homerjam I think that's what https://github.com/ladjs/node-email-templates/pull/228 intended, though at first glance of his PR it's a completely new file or something, which is a lot to add to the codebase for 2.x at least.

**Comment by homerjam** [comment]
Yep similar intentions, and confusing PR! But if you're planning a promise based re-write then separating out the templating loading would allow us to add file/db/http loaders - hopefully covering all bases!

**Comment by simllll** [comment]
As mentioned in another issue, I really would like to see a feature to specify custom templates.
Right now they are limited to a predefined set of 'html', 'text', 'style', 'subject', 'deeplink'. All of them (or at least some) have their own "policy" to process something. It would give great flexibility to this module to dynamically add other types. So people can use it not only for "mails", also for e.g. push notifications, messaging templates, etc..

thanks
simon

**Comment by Vishal1419** [comment]
Support for Images and 
Bootstrap

**Comment by gbourne1** [comment]
Along the lines of what @homerjam requested, loading the template from an in memory object.  A use case is when you've done pre-processing on the template (e.g. merged several templates into a single one) and now want to pass the template object to email-template.

**Comment by niftylettuce** [comment]
@gbourne1 @homerjam I've released v3.0.0, try it out and see updated docs here <https://github.com/niftylettuce/node-email-templates> (let me know of your questions - I wrote up a Database example for you in the README).
