### ISSUE TITLE
The api should be a bit more modular.

### ISSUE THREAD

**Issue by nathanbowser** [niftylettuce/node-email-templates#31]
Having to call emailTemplate(dir, next) every time you want to process some templates introduces a lot of overheard. It would be nice if the templates could be cached.

**Comment by StephanHoyer** [comment]
what about 

```javascript
var emailTemplates = require('email-templates');
var template = emailTemplates(templatesDir);

template('my_fancy-email', locals, function(err, html, text) {
})
```

that would allow to do this:

```javascript
var emailTemplates = require('email-templates');
var template = emailTemplates(templatesDir);

module.exports = function(locals, done) {
  template('my_fancy-email', locals, done)
});
```

The parsing can be done once and exporting the thing is much easier.

**Comment by StephanHoyer** [comment]
One can use promises, but thats a lot of boiler plate.

Maybe lib should utilize promises.

```javascript
'use strict';

var path = require('path');
var templatesDir = path.join(__dirname, 'templates');
var emailTemplates = require('email-templates');

var api = {};

var parsedTemplates;
function init() {
  if (parsedTemplates) {
    Promise.resolve(parsedTemplates);
  }
  return new Promise(function(resolve, reject) {
    emailTemplates(templatesDir, function(err, template) {
      if (err) {
        reject(err);
      }
      parsedTemplates = template;
      resolve(template);
    });
  });
}

api.confirm = function(locals) {
  return init().then(function(template) {
    return new Promise(function(resolve, reject) {
      template('confirm', locals, function(err, html, text) {
        if (err) {
          reject(err);
        }
        resolve({
          html: html,
          text: text
        });
      });
    });
  }).then(console.log.bind(console));
};

module.exports = api;
```

**Comment by StephanHoyer** [comment]
just created a [module](https://www.npmjs.com/package/email-templates-as-promised) for that

**Comment by clarkbw** [comment]
> I do believe consolidate has a template cache, will look into it to close this issue.

@jeduan consolidate does have caching, https://github.com/tj/consolidate.js#caching
When passing in the locals object you should be able to add ` { cache: true, other: 'local variables' }` to the locals object to instruct consolidate to cache the template.  The consolidate cache does depend on your choice of engine supporting caching.

I'm testing this out right now, assuming it works a simple change to the README should suffice.

**Comment by jeduan** [comment]
Ok, so v2 is the work of thinking about this. Please check out the branch https://github.com/niftylettuce/node-email-templates/tree/v2.0

The API is now fully Promise-based @StephanHoyer 

I'll be closing this. Please reopen if you have any more thoughts.
