### ISSUE TITLE
Share styles between templates

### ISSUE THREAD

**Issue by ragulka** [niftylettuce/node-email-templates#39]
Is it somehow possible to share common styles between templates? For example - header and footer styling?

**Comment by Philmod** [comment]
Hey guys,

Is there a way to share the style file (`style.css`) for all the templates? For example by putting it in the root templates directory.

Thanks,
Philmod

**Comment by niftylettuce** [comment]
Yes, you can do something like this...

Folder named `./emails/`.  Inside of it you have different email templates, e.g. `./emails/welcome-message/` and `./emails/forgot-password/`.  Each of these folders has `html.ejs` of course and then an accompanying stylesheet `style.less`.  At the top of `style.less` you have a line such as `@import "../style.less";` which would import a global stylesheet located at `./emails/style.less`.
