### ISSUE TITLE
final callback after batch is done

### ISSUE THREAD

**Issue by timsuchanek** [niftylettuce/node-email-templates#58]
Hey,
is there a possibility to get a final callback after the batch is done?
I'm calling this as a module and would like to have a kind of interface, so I can handle the response.

Thanks
Tim

**Comment by jeduan** [comment]
Starting with 2.0 you can now use promises in the API, so you could use `Promise.all` to receive a notification when all the templates have rendered, [similar to this example](https://github.com/niftylettuce/node-email-templates/tree/v2.0#basic)
