### ISSUE TITLE
Empty email when stylesheet present

### ISSUE THREAD

**Issue by softwarerero** [niftylettuce/node-email-templates#72]
I can send an email using Jade without problems as long as no stylesheet is present. As soon as I put a stylesheet (style.css or style.less) in the template directory a call to ```template``` produces an empty html document:
``` <!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"></html>```.

The stylesheet is not really spectacular, here it is in its full beauty:
```body { background-color: white;}```

I do not get any error. Any ideas how this can be debugged?

**Comment by jeduan** [comment]
Please reopen if issue still persists
