### ISSUE TITLE
ENOENT when using only a text template

### ISSUE THREAD

**Issue by karma0** [niftylettuce/node-email-templates#97]
The following error is returned after creating a text.ejs file without an html.ejs or style.ejs in the same directory:

    [Error: ENOENT, stat ''] errno: 34, code: 'ENOENT', path: ''

Adding an empty html.ejs doesn't seem to help, but renaming the text file to html.ejs works.

**Comment by jeduan** [comment]
Closing as related PR is closed. If still persists please add a new issue.
